server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/project?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: hadanhdao
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "2UTZkhYCZ+iiCQlu+nJH3SpVqGNoTihNTYdhkNxEz0ax46HNYFEawbAcwT7YKeFK"

app:
  services:
    profile: http://localhost:8081/profile
